### ISSUE TITLE
Invalid definition for ActiveStorage 6.1

### ISSUE THREAD

**Issue by clinejj** [ruby/gem_rbs_collection#128]
When including ActiveStorage in a Steepfile, the following error occurs:

```sh
gem_rbs/gems/activestorage/6.1/app/models/active_storage/blob.rbs:166:42: [error] Cannot find type `Tempfile`
│ Diagnostic ID: RBS::UnknownTypeName
│
└   def open: (?tmpdir: untyped? tmpdir) { (Tempfile) -> untyped } -> untyped
```

Line in question: https://github.com/ruby/gem_rbs_collection/blob/7726d637c93032cf8759dc6fd9196b5caaffc7df/gems/activestorage/6.1/app/models/active_storage/blob.rbs#L166

Method Definition from rails:
https://github.com/rails/rails/blob/d38ff07a39c98f5db2b15ca3a51acee48c972205/activestorage/app/models/active_storage/blob.rb#L275-L278

It seems the signature should be updated to:
```rb
def open: (?tmpdir: untyped? tmpdir) { (untyped) -> untyped } -> untyped
```

**Comment by ksss** [comment]
@clinejj Hi. I wrote its signature.

Do you use rbs collection?

The activestorage 6.1 dir has manifest.yaml.
https://github.com/ruby/gem_rbs_collection/blob/main/gems/activestorage/6.1/manifest.yaml

The manifest.yaml helps to automatically import dependent stdlibs when using the rbs collection.
If you are not using rbs collection, Importing tempfile solves this problem.

The signature is not wrong.

https://github.com/rails/rails/blob/e75682b0f84c6ad607c62ea377b69876fd13f32d/activestorage/lib/active_storage/downloader.rb#L11-L17

**Comment by pocke** [comment]
Thanks for reporting the issue 👍 

I agree with @ksss's comment. You can avoid the error with `rbs collection`. It loads tempfile's signature.


The documentation of `rbs collection` is here https://github.com/ruby/rbs/blob/master/docs/collection.md
If you have any question, feel free to ask me.

Thanks.

**Comment by clinejj** [comment]
Gotcha, and apologies for the delay in responding. We're not using `rbs collection` yet - I'll close and reopen if we run into issues after we switch. Thanks!
