### ISSUE TITLE
Non-overloading method of `#to_time` in `Time::` on ActiveSupport

### ISSUE THREAD

**Issue by clinejj** [ruby/gem_rbs_collection#177]
After updating to the latest RBS/Steep versions (2.6.0 and 1.0.1 respectively), we are getting the following error after running `steep check`: 

```sh
.gem_rbs_collection/activesupport/6.0/activesupport-generated.rbs:6115:2: [error] Non-overloading method definition of `to_time` in `::Time` cannot be duplicated
│ Diagnostic ID: RBS::DuplicatedMethodDefinition
│
└   def to_time: () -> untyped
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

see:
https://github.com/ruby/gem_rbs_collection/blob/cd6db41310b911e1df3476246257510673f01b8a/gems/activesupport/6.0/activesupport-generated.rbs#L6110-L6116

This was added in RBS 2.6.0 at https://github.com/ruby/rbs/pull/1033 by @ksss, but the type definitions here have not been updated for ActiveSupport

**Comment by ksss** [comment]
Good catch!
I'll fix soon!
