### ISSUE TITLE
Cannot find type `ActiveModel::Errors`

### ISSUE THREAD

**Issue by skyksandr** [ruby/gem_rbs_collection#188]
みんなさんこんにちは。
アレクサンダーです。
~日本語~RBSを勉強してる。

I installed `rbs`, `rbs collection`, added `activemodel` to `rbs_collection.yaml`

Then, I created type for controller concern module like this:
```
module EventScoped
  extend ActiveSupport::Concern

  ...
  def respond_with_errors: (ActiveModel::Errors errors) -> void
  ...
end
```

However I'm getting error:
```
app/controllers/concerns/event_scoped.rbs:12:28: [error] Cannot find type `ActiveModel::Errors`
│ Diagnostic ID: RBS::UnknownTypeName
│
└   def respond_with_errors: (ActiveModel::Errors errors) -> void
                              ~~~~~~~~~~~~~~~~~~~
```

I see `ActiveModel::Errors` defined in `activemodel/6.0/activemodel-generated.rbs`
But do not understand why `steep` do not see this definition.

Could you please help me make it work?

**Comment by pocke** [comment]
Hmm, I couldn't reproduce it. Could you explain more information? The following information will be helpful.

* contents of the following files:
  * Steepfile
  * rbs_collection.yaml and rbs_collection.lock.yaml
* Versions of
  * rbs
  * steep
  * ruby

**Comment by skyksandr** [comment]
I'm sorry @pocke, I forgot to update this issue. 
Soutaro helped me with it by upgrading RBS, steep and gems in rbs_colleciton and it is no longer reproducible.
