### ISSUE TITLE
Process for generating types for new aws-sdk gems

### ISSUE THREAD

**Issue by G-Rath** [ruby/gem_rbs_collection#190]
I'm using `aws-sdk-ssm` and would love to have types for that - I've seen there's a [generator](https://github.com/ruby/gem_rbs_collection/tree/main/generators/aws-sdk-rbs-generator) but I don't see how it correlates with the handful of `aws-sdk` gems that are in this repo? i.e. I don't see anywhere a list that has just the clients that are currently here, but then this repo doesn't already have every aws client.

What's the process for generating the types for new clients?

**Comment by ksss** [comment]
@G-Rath 
Thank you for the feedback!
This is the first feedback and I am really pleased.
I created the PR. Please feel free to give me feedback on its use also.

https://github.com/ruby/gem_rbs_collection/pull/191

**Comment by G-Rath** [comment]
@ksss thanks for the fast response and PR! it looks good to me - I've made a comment about one aspect that I think the docs should cover, but the types themselves look great!

**Comment by ksss** [comment]
@G-Rath 
I have generated an RBS for `aws-sdk-ssm` https://github.com/ruby/gem_rbs_collection/pull/191 .
Feel free to let me know if you have any problems.
