### ISSUE TITLE
Conflict with rbs update in Steep

### ISSUE THREAD

**Issue by greginos** [ruby/gem_rbs_collection#25]
The rbs update creates a conflict with gem_rbs_collection.
The error message : 
`::Hash#except has duplicated definitions`

I had to comment the two definitions (except and except!) to remove the conflict but it is just a workaround.
````
# gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs
# line 3327

class Hash[unchecked out K, unchecked out V]
  # Returns a hash that includes everything except given keys.
  #   hash = { a: true, b: false, c: nil }
  #   hash.except(:c)     # => { a: true, b: false }
  #   hash.except(:a, :b) # => { c: nil }
  #   hash                # => { a: true, b: false, c: nil }
  #
  # This is useful for limiting a set of parameters to everything but a few known toggles:
  #   @person.update(params[:person].except(:admin))
  def except: (*untyped keys) -> untyped

  # Removes the given keys from hash and returns it.
  #   hash = { a: true, b: false, c: nil }
  #   hash.except!(:c) # => { a: true, b: false }
  #   hash             # => { a: true, b: false }
  def except!: (*untyped keys) -> untyped
end
````

Should I open an issue on rbs too ?
Thanks

**Comment by greginos** [comment]
Error message with `steep check` command :  
` UnexpectedError: /.rvm/gems/ruby-3.0.0/gems/rbs-1.2.0/core/hash.rbs:459:2...459:34: ::Hash#except has duplicated definitions in /vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:3336:2...3336:40 `

**Comment by pocke** [comment]
Thanks for reporting the issue. 

I think we need to remove the `except` and `except!` definitions in gem_rbs_collection. Currently, RBS focuses only on the latest Ruby, so we can assure `Hash#except` exists in the standard library.


I'll remove the duplicated definitions.

Thanks

**Comment by greginos** [comment]
Thank you very much, and thanks for all you do with rbs 😄
