### ISSUE TITLE
Activesupport unknown types

### ISSUE THREAD

**Issue by tibbon** [ruby/gem_rbs_collection#32]
I submodule included these as suggested in the `README.md`, but I'm getting a bunch of errors that I didn't expect.

My project uses ActiveSupport `6.1.3.2`

```
target :lib do
  repo_path "vendor/rbs/gem_rbs_collection/gems"
  signature "sig"
  check "lib"                       # Directory name
  ignore "lib/main.rb"
  ignore "vendor/**/*.rb"
  
  library "set"
  library "time"
  library "json"
  library "redis"
  library "activesupport"
end
```

```
bundle exec steep check
# Type checking files:

.................F....................................................................

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:1786:4: [error] Cannot find type `Monitor`
│ Diagnostic ID: RBS::UnknownTypeName
│
└     class LoadInterlockAwareMonitor < Monitor
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:1805:6: [error] Cannot find type `MonitorMixin`
│ Diagnostic ID: RBS::UnknownTypeName
│
└       include MonitorMixin
        ~~~~~~~~~~~~~~~~~~~~

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:7133:4: [error] Cannot find type `Singleton`
│ Diagnostic ID: RBS::UnknownTypeName
│
└     include Singleton
      ~~~~~~~~~~~~~~~~~

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:8888:8: [error] Cannot find type `::Logger::Severity`
│ Diagnostic ID: RBS::UnknownTypeName
│
└         include ::Logger::Severity
          ~~~~~~~~~~~~~~~~~~~~~~~~~~

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:9016:2: [error] Cannot find type `::Logger`
│ Diagnostic ID: RBS::UnknownTypeName
│
└   class Logger < ::Logger
    ~~~~~~~~~~~~~~~~~~~~~~~

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:9031:4: [error] Cannot find type `::Logger::Formatter`
│ Diagnostic ID: RBS::UnknownTypeName
│
└     class SimpleFormatter < ::Logger::Formatter
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

vendor/rbs/gem_rbs_collection/gems/activesupport/6.0.3.2/activesupport-generated.rbs:9697:6: [error] Cannot find type `Mutex_m`
│ Diagnostic ID: RBS::UnknownTypeName
│
└       include Mutex_m
        ~~~~~~~~~~~~~~~

Detected 7 problems from 1 file
```

**Comment by tibbon** [comment]
I downgraded my ActiveSupport to see if it made a difference at `6.0.3.2` but no luck, same errors

**Comment by pocke** [comment]
Thanks for reporting issue!


Currently you need to specify dependency of `activesupport` gem explicitly in `Steepfile`.
You can find the dependency list from here: https://github.com/pocke/rbs_rails#steep-integration The documentation is for full of Rails gems, so maybe you don't need some gems in the list if you only need `activesupport` gem.


By the way, I know the current behavior is not smart. RBS should be useful even if the user doesn't know all dependencies.
I'm working on `rbs collection` command to solve this problem on https://github.com/ruby/rbs/pull/589. This command solves this problem (maybe partially). We are also considering to introduce a file to write RBS's dependencies for rbs repository, such as `manifest.yaml`.

**Comment by tibbon** [comment]
I've already got `library "activesupport"`- is there something else to add there?

**Comment by pocke** [comment]
> I've already got `library "activesupport"`- is there something else to add there?

Yes, `library "activesupport"` is not enough to use `activesupport` gem's RBS unfortunately.
If you want to use `activesupport` gem, you need to write `lirbary "activesupport"` and `library` for activesupport's dependencies, such as `library "monitor"` `library "logger"`, etc

**Comment by tibbon** [comment]
Ah, that makes sense! It doesn't chain dependencies automatically. I might think about how to best document this and put in a PR for that documentation change.

**Comment by pocke** [comment]
I've implemented `rbs collection` and `manifest.yaml` feature to fix this problem.
Now we can use `rbs collection` instead of resolving dependencies by hand.

For more information, see the document. https://github.com/ruby/rbs/blob/master/docs/collection.md
