### ISSUE TITLE
Adding types for webrick, nats, grpc

### ISSUE THREAD

**Issue by iurev** [ruby/gem_rbs_collection#328]
Hello!
I am interested in adding types for webrick, nats and grpc to this repository ☺️.
If you think that this is a good idea, please, write me and I will start working on a PR with webrick types to demonstrate how it would look like.

**Comment by pocke** [comment]
Thanks for your contribution! 

> If you think that this is a good idea, 

Sure! Please write the types 👍 


------

I'll close this issue. Feel free to open PRs on this repository.
