### ISSUE TITLE
[Documentation] Runtime testing using filename

### ISSUE THREAD

**Issue by raosush** [ruby/gem_rbs_collection#40]
# Description
* RBS does not support filename based runtime testing using CLI command `rbs test`

# Explanation
* RBS uses [Open3.capture3](https://github.com/ruby/rbs/blob/9c6bf443d3fba5506734eb4bfe27c0915dad64af/lib/rbs/cli.rb#L821) to run a command for executing runtime tests.
* If a filename is passed as an argument to `rbs test` command, `Open3.capture3` executes the filename as a command, due to which a `Permission denied error` is thrown.
![image](https://user-images.githubusercontent.com/57192414/126030707-b85f32b7-c0de-44dc-9cfb-92705fdc83ca.png)
* This error is because a filename cannot be executed as a command, using `Open3.capture3`, which throws permission denied error.

**Comment by soutaro** [comment]
How about `$ rbs test ruby test.rb` ?

**Comment by raosush** [comment]
Closing this as ruby/gem_rbs_collection#41 is merged.
