### ISSUE TITLE
Add Japanese translation to Contribution Guide

### ISSUE THREAD

**Issue by ybiquitous** [ruby/gem_rbs_collection#560]
Hi RBS folks, 👋🏼 

Have you enjoyed RubyKaigi 2024 in Okinawa? I enjoyed it so much! 😄 

By the way, I heard a similar opinion there from some Japanese friends: "I am interested in contributing to ruby/gem_rbs_collection, but I still have some barriers."

So, what about adding a Japanese translation to the existing Contribution Guide so that the community can accept more contributors?

Here's the current guide: https://github.com/ruby/gem_rbs_collection/blob/438153d157e1e1ed6b640da973e33f333e57e6d9/docs/CONTRIBUTING.md
A new translated guide: `docs/CONTRIBUTING.ja.md` (just an idea)

For an example of such translations, we can see ruby/ruby: https://github.com/ruby/ruby/blob/2d4d99f78aa846b21f05508ab73172b24bd08954/README.ja.md

I see that this addition might increase our maintenance cost at some level, but I believe more newcomers could help maintain the new translated guide.

I'd appreciate any feedback/opinions/thoughts on this suggestion. 🙏🏼

**Comment by pocke** [comment]
I'm a bit negative due to the maintenance cost, as you said. We have many translation tools such as DeepL, Google Translate, and LLM BOTs. Contributors can read the guide in their mother tongue easily with these tools. 

Personally, I think we should spend time describing the contribution process in detail.

BTW, I'm not against unofficially translating the document.

**Comment by ybiquitous** [comment]
@pocke Thanks for the feedback! Yeah, I see that modern translation tools (using LLM) could help reduce contribution barriers from Japanese people 👍🏼 

> I think we should spend time describing the contribution process in detail.

Totally agree 👍🏼 

---

To be accurate, we should keep the current contribution guide in English and consider it an original. I imagine the Japanese version would follow the English version with the community's help.

**Comment by sue445** [comment]
I agree with @pocke too.

I have created patches to this repository several times.

IMO, I thought it would be easier to throw out a PR if there was a [Pull Request Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) regarding common use cases (e.g. adding new rbs).

**Comment by ybiquitous** [comment]
> IMO, I thought it would be easier to throw out a PR if there was a [Pull Request Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) regarding common use cases (e.g. adding new rbs).

@sue445 Great feedback! I agree with adding a PR template. It should make it easier to create a PR. 👍🏼 (although it's out of scope of this issue)

**Comment by ybiquitous** [comment]
There does not seem to be any positive feedback, so I'm closing this.
Thanks for the comments, guys!
