### ISSUE TITLE
When set Retryable's option, UnexpectedError occurred.

### ISSUE THREAD

**Issue by kyanagimoto** [ruby/gem_rbs_collection#84]
I tried to use gem_rbs_collection w/ [this code](https://github.com/kyanagimoto/try_typoprof/tree/97d00cde823fc83b338b8cb2186f0aae669240c3),
then UnexpectedError happened on Retryable steep check in [this code](https://github.com/kyanagimoto/try_typoprof/blob/97d00cde823fc83b338b8cb2186f0aae669240c3/runner/fizz_buzz_runner.rb#L7)

![Screen Shot 2021-11-05 at 15 30 42](https://user-images.githubusercontent.com/388192/140468150-442712ad-1b6f-45fb-99d8-b671a280ae96.png)

If I did Retryable configuration w/

```ruby
Retryable.configure do |config|
  config.sleep = 1
end

Retryable.retryable do
  results = FizzBuzz.run(Date.today.day)
  puts results
end
```

it worked.

Do you have any idea to avoid this  Diagnostic ID: Ruby::UnexpectedError?

**Comment by ksss** [comment]
Probably it's this problem.
https://github.com/soutaro/steep/issues/429

**Comment by kyanagimoto** [comment]
I see.
Now I close this issue.

Thank you to let me know.
