### ISSUE TITLE
Missing ActiveSupport::Duration

### ISSUE THREAD

**Issue by wagenet** [ruby/gem_rbs_collection#93]
https://api.rubyonrails.org/classes/ActiveSupport/Duration.html

**Comment by ksss** [comment]
@wagenet Hi.

You can see `ActiveSupport::Duration` methods here.
https://github.com/ruby/gem_rbs_collection/blob/2902a6537e946663f86084d32bb04b5e2a132620/gems/activesupport/6.0.3.2/activesupport-generated.rbs#L7225

However, many types are currently untyped.

**Comment by wagenet** [comment]
Oh strange, sorry about that. I somehow missed it!
