### ISSUE TITLE
Redis is missing `zadd` and possibly more

### ISSUE THREAD

**Issue by wagenet** [ruby/gem_rbs_collection#98]
https://rubydoc.info/gems/redis/Redis#zadd-instance_method

**Comment by pocke** [comment]
Thanks for reporting the issue.

Currently this repository accepts incomplete type definitions, so they may include missing methods often.
Adding method definitions is welcome. Feel free to open a PR :raised_hands:

**Comment by pocke** [comment]
I'll close this issue. `zadd` method has been added by #271, and this repository doesn't focus on complete type definitions. I think we don't need to open individual issues for missing methods, but PRs are welcome!
